# -*- coding: utf-8 -*-
"""Business_Sales_Intelligence_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXdNbcUdXTY3Akj-20_B5j-j6xv8wfOO

# Business Sales Intelligence Dashboard

## Project Objective: -

The objective of this project is to analyze Superstore sales data using Python and Pandas to identify sales trends, profitable products, customer segments, regional performance, shipping patterns, and business opportunities.

The project concludes with business recommendations supported by data.

## Business Questions: -

This project aims to answer the following questions in the order of analysis:

1. Which product category generates the highest sales revenue?
2. Which specific product generates the highest sales revenue?
3. Which category earns the highest profit?
4. Which product causes the highest loss?
5. Which category receives the highest average discount?
6. Does higher discount reduce profit?
7. Which region has the lowest average profit?
8. Which customer segment generates the highest total sales?
9. Which customer segment generates the highest total profit?
10. Which shipping mode is used the most?

## Tools Used

- Python
- Pandas
- Google Colab

## Dataset

This project uses the Superstore Sales dataset containing 9,994 retail transactions.

The dataset includes information about:

- Products
- Customers
- Sales
- Profit
- Discounts
- Regions
- Shipping
- Dates
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("Superstore.csv", encoding="latin1")

"""# SECTION 1 : Dataset Understanding"""

df.head()

df.tail()

df.columns

df.shape

df.info()

df.describe()

"""# SECTION 2 : Sales Analysis

## Business Question 1

### Which Product Category Generates the Highest Sales Revenue?
"""

print(df.groupby("Category")["Sales"].sum().idxmax())

"""## Business Question 2

### Which Product Generates the Highest Sales Revenue?
"""

print(df.groupby("Product Name")["Sales"].sum().idxmax())

"""##Top 10 Products by Sales: -"""

print(df.groupby(["Product Name","Category"])["Sales"].sum().sort_values(ascending=False).head(10))

# Data preparation
top_10_products = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10).reset_index()

# Ultra-simple Plot
plt.figure(figsize=(10, 5))
sns.barplot(data=top_10_products, y='Product Name', x='Sales', color='skyblue')

# Remove all non-essential elements
sns.despine(left=True, bottom=True)
plt.tick_params(left=False, bottom=False)
plt.title('Top 10 Products by Sales', fontsize=12, loc='center', color='black')
plt.xlabel('')
plt.ylabel('')

plt.show()

"""## Average Sales per Category"""

print(df.groupby("Category")["Sales"].mean())

"""### Visualizing Sales by Category"""

# Data
category_sales = df.groupby('Category')['Sales'].mean().reset_index()

# Ultra-simple Plot
plt.figure(figsize=(6, 3))
sns.barplot(data=category_sales, x='Category', y='Sales', color='skyblue')

# Remove all non-essential elements
sns.despine(left=True, bottom=True)
plt.tick_params(left=False, bottom=False)
plt.title('Sales by Category', fontsize=12, loc='center', color='black')
plt.xlabel('')
plt.ylabel('')

plt.show()

"""# SECTION 3 : Profit Analysis

## Business Question 3

### Which Category earns the highest Profit?
"""

print(df.groupby("Category")["Profit"].sum().idxmax())

"""## Business Question 4

### Which Product causes the highest Loss?
"""

print(df.groupby("Product Name")["Profit"].sum().idxmax())

"""## Top 10 Most Profitable Products"""

print(df.groupby(["Product Name","Category"])["Profit"].sum().sort_values(ascending=False).head(10))

"""### Visualizing Profit by Category"""

# Data
category_profit = df.groupby('Category')['Profit'].mean().reset_index()

# Ultra-simple Plot (Matching Sales Style)
plt.figure(figsize=(6, 3))
sns.barplot(data=category_profit, x='Category', y='Profit', color='skyblue')

# Remove all non-essential elements
sns.despine(left=True, bottom=True)
plt.tick_params(left=False, bottom=False)
plt.title('Profit by Category', fontsize=12, loc='center', color='black')
plt.xlabel('')
plt.ylabel('')

plt.show()

"""## Profit by Sub-Category"""

print(df.groupby('Sub-Category')['Profit'].sum().sort_values(ascending=False).head(3))

"""## Loss by Sub-Category"""

print(df.groupby('Sub-Category')['Profit'].sum().sort_values(ascending=True).head(3))

"""# SECTION 4 : Discount Analysis

## Average Discount by Category: -
"""

print(df.groupby("Category")["Discount"].mean().sort_values(ascending=True))

"""## Business Question 5

### Which Category receives the highest Discount?
"""

print(df.groupby("Category")["Discount"].sum().idxmax())

"""## Business Question 6

### Does higher Discount reduce Profit?
"""

print(df.groupby("Discount")["Profit"].sum())

"""Yes!! it does.

# SECTION 5 : Regional Analysis

## Highest Sales Region
"""

print(df.groupby("Region")["Sales"].sum().idxmax())

"""### Visualizing Sales by Region"""

# Data
region_sales = df.groupby('Region')['Sales'].mean().reset_index()

# Ultra-simple Plot (Matching established style)
plt.figure(figsize=(6, 3))
sns.barplot(data=region_sales, x='Region', y='Sales', color='skyblue')

# Remove all non-essential elements
sns.despine(left=True, bottom=True)
plt.tick_params(left=False, bottom=False)
plt.title('Sales by Region', fontsize=12, loc='center', color='black')
plt.xlabel('')
plt.ylabel('')

plt.show()

"""## Highest Profit Region"""

print(df.groupby("Region")["Profit"].sum().idxmax())

"""## Lowest Profit Region"""

print(df.groupby("Region")["Profit"].sum().idxmin())

"""## Average Sales per Region"""

print(df.groupby("Region")["Sales"].mean())

"""## Category with highest Sales in every Region"""

print(df.groupby(["Region", "Category"])["Sales"].sum().groupby(level=0, group_keys=False).nlargest(1))

"""## Average Sales of each Category in every Region"""

print(df.groupby(["Region", "Category"])["Sales"].mean())

"""## Business Question 7

### Which Region has the lowest average Profit?
"""

print(df.groupby("Region")["Profit"].mean().idxmin())

"""# SECTION 6 : Customer Segment Analysis

## Business Question 8

### Which Segment generates highest Sales?
"""

print(df.groupby("Segment")["Sales"].sum().idxmax())

"""## Business Question 9

### Which Segment generates highest Profit?
"""

print(df.groupby("Segment")["Profit"].sum().idxmax())

"""## Average Sales per Segment"""

print(df.groupby("Segment")["Sales"].mean())

"""## Product Segment Analysis"""

print(df.groupby('Segment').agg({'Sales': 'mean', 'Profit': 'sum'}).sort_values(by='Sales', ascending=False))

"""# SECTION 7 : Shipping Analysis

## Business Question 10

### Which Ship Mode is used the most?
"""

print(df["Ship Mode"].value_counts().idxmax())

"""## Average Profit by Ship Mode"""

print(df.groupby("Ship Mode")["Profit"].mean())

"""### Visualizing Ship Mode Usage"""

# Data
ship_mode_counts = df['Ship Mode'].value_counts().reset_index()
ship_mode_counts.columns = ['Ship Mode', 'Count']

# Ultra-simple Plot
plt.figure(figsize=(6, 3))
sns.barplot(data=ship_mode_counts, x='Ship Mode', y='Count', color='skyblue')

# Remove all non-essential elements
sns.despine(left=True, bottom=True)
plt.tick_params(left=False, bottom=False)
plt.title('Ship Mode Usage Count', fontsize=12, loc='center', color='black')
plt.xlabel('')
plt.ylabel('')

plt.show()

"""## Average Sales by Ship Mode"""

print(df.groupby("Ship Mode")["Sales"].mean())

"""## Ship Mode Usage & Profit"""

print(df.groupby('Ship Mode').agg({'Profit': ['count', 'sum', 'mean']}))

"""# SECTION 8 : Time Analysis"""

df['Order Date'] = pd.to_datetime(df['Order Date'])
# df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month_name()

"""## Sales by Year"""

print(df.groupby("Year")["Sales"].sum())

"""## Profit by Year"""

print(df.groupby("Year")["Profit"].sum())

"""## Sales by Month"""

month_order = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

print(df.groupby("Month")["Sales"].sum().reindex(month_order))

"""### Visualizing Sales by Month"""

# Data preparation
monthly_sales = df.groupby("Month")["Sales"].sum().reindex(month_order).reset_index()

# Ultra-simple Plot
plt.figure(figsize=(10, 4))
sns.barplot(data=monthly_sales, x='Month', y='Sales', color='skyblue')

# Remove all non-essential elements
sns.despine(left=True, bottom=True)
plt.tick_params(left=False, bottom=False)
plt.title('Total Sales by Month', fontsize=12, loc='center', color='black')
plt.xlabel('')
plt.ylabel('')
plt.xticks(rotation=45)

plt.show()

"""## Month with highest Sales"""

print(df.groupby("Month")["Sales"].sum().idxmax())

"""## Month with Lowest Sales"""

print(df.groupby("Month")["Sales"].sum().idxmin())

"""# SECTION 9: Business Recommendations

#### **Observation 1**
> **Technology** contributes the highest sales and profit among all product categories.

#### **Interpretation**
> This suggests that technology products have strong customer demand and play a major role in the company's revenue.

#### **Recommendations**
>*   **Inventory Management:** Maintain sufficient inventory levels of technology products to meet consistent demand.
>*   **Marketing Focus:** Prioritize marketing campaigns and promotional activities on high-performing technology items.
>*   **Stock Optimization:** Implement rigorous monitoring to ensure popular products remain in stock at all times.

#### **Expected Impact**
>*   **Increased revenue**
>*   **Reduced stock-outs**
>*   **Higher customer satisfaction**

#### **Observation 2**
> **Furniture** consists of highest discount among all product categories.

#### **Interpretation**
> This shows the reason for furniture category to have such a low profit among other categories as well as company's revenue.

#### **Recommendations**
>*   **Marketing Focus:** Prioritize marketing the combinations of low-performing furniture items with the items of other product categories.
>*   **Discount Optimization:** Re-evaluate the discounts to ensure the increase in profit of high-performing furniture items.

#### **Expected Impact**
>*   **Increased revenue**
>*   **Maintain constant stock supply**
>*   **Higher customer satisfaction**

#### **Observation 3**
> **Central** region has lowest sales compared to other regions.

#### **Interpretation**
> This shows that either there is not enough marketing of the products or there is shortage of products in our shops in **Central** region, it can cause depletion in company's revenue .

#### **Recommendations**
>*   **Marketing Focus:** Prioritize marketing every Products near every shop or our company in **Central** region.
>*   **Maintain Adequate Stock:** Make sure that shops from **Central** region keeps a constant and proper supply of products in their warehouses.

#### **Expected Impact**
>*   **Increased revenue**
>*   **Maintain constant stock supply**

#### **Observation 4**
> **Tables** and **Bookcases** are causing the most losses even though they have high sales.

#### **Interpretation**
> This shows that these specific items are either priced too low or the costs for shipping and discounts are too high, causing the company to lose money on them.

#### **Recommendations**
>*   **Price Adjustment:** Increase the base price of Tables and Bookcases to make sure we aren't selling them at a loss.
>*   **Shipping Fees:** Add a shipping fee for these heavy items to help cover the high delivery costs.
>*   **Bundle Deals:** Only give discounts on these items when they are bought together with high-profit Technology products.

#### **Expected Impact**
>*   **Better profit margins**
>*   **Reduced losses on furniture**

#### **Observation 5**
> **Standard Class** is the most popular shipping method but brings in the lowest average profit.

#### **Interpretation**
> This shows that while most customers prefer the cheapest shipping, the profit margin is very small, making it risky if shipping costs go up.

#### **Recommendations**
>*   **Encourage Upgrades:** Offer small deals to get customers to choose 'Second Class' or 'First Class' shipping instead.
>*   **Logistics Deals:** Negotiate better rates with shipping companies for high-volume Standard Class orders to save money.

#### **Expected Impact**
>*   **Higher profit per order**
>*   **More efficient shipping costs**

#### **Observation 6**
> **Corporate** and **Home Office** customers spend more on average per order than regular Consumers.

#### **Interpretation**
> This shows that while we have more regular customers, business clients buy more expensive items or larger amounts at once, which is better for revenue.

#### **Recommendations**
>*   **B2B Support:** Create special accounts or paths for Corporate clients to make it easier for them to place large orders.
>*   **Targeted Ads:** Focus more ads on Home Office setups, showing them bundles of high-value equipment.

#### **Expected Impact**
>*   **Higher average sales per order**
>*   **Better sales efficiency**

# Conclusion

This analysis shows that **Technology** is our strongest area, while **Furniture** needs better pricing and discount management to stop losing money.

Since most customers use **Standard Class** shipping, finding ways to make it more efficient is key to increasing our profit.

We also saw that some regions perform much better than others, which gives us a clear idea of where to invest more in the future.

Overall, these data-driven insights give us a clear path to help the business grow and become more profitable.
"""